// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC01Rn8axaiSiDZaSFVzpRRNuSUGXgo1KY',
    appId: '1:139895693353:web:063e5008dc0b1d5f4bbc38',
    messagingSenderId: '139895693353',
    projectId: 'fir-58abe',
    authDomain: 'fir-58abe.firebaseapp.com',
    storageBucket: 'fir-58abe.appspot.com',
    measurementId: 'G-QQSZZQ2WFN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBOCjmIMArqGGykFFog7h2LCnVSyfxBjw',
    appId: '1:139895693353:android:579f43a4682d08444bbc38',
    messagingSenderId: '139895693353',
    projectId: 'fir-58abe',
    storageBucket: 'fir-58abe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFFL4C1I1Et0PIO5s-jAYP-whdCkdqXLs',
    appId: '1:139895693353:ios:8b1e15fb1c0b76034bbc38',
    messagingSenderId: '139895693353',
    projectId: 'fir-58abe',
    storageBucket: 'fir-58abe.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFFL4C1I1Et0PIO5s-jAYP-whdCkdqXLs',
    appId: '1:139895693353:ios:8b1e15fb1c0b76034bbc38',
    messagingSenderId: '139895693353',
    projectId: 'fir-58abe',
    storageBucket: 'fir-58abe.appspot.com',
    iosBundleId: 'com.example.firebase',
  );
}
